alias grep='grep --color=auto'
alias v='vim'
alias la='ls -a'
alias less='less -N'
alias m='less -N'
alias tmux='tmux -2u'
alias atom='/Applications/Atom.app/Contents/MacOS/Atom'
alias apm='/Applications/Atom.app/Contents/Resources/app/apm/bin/apm'
