alias grep='grep --color=auto'
alias vi='vim'
alias la='ls -a'
alias less='less -N'
alias m='less -N'
alias tmux='tmux -2u'
alias atom='/Applications/Atom.app/Contents/MacOS/Atom'
alias mysql='/Applications/MAMP/Library/bin/mysql'
